services:
  telegram-review-bot:
    container_name: telegram-review-bot
    image: telegram-review-bot
    build:
      context: ./telegram-review-bot
      dockerfile: Dockerfile
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_URL=${MINIO_URL}
      - MINIO_SECURE=${MINIO_SECURE}
      - BOT_TOKEN=${BOT_TOKEN}
  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./persistence/minio/:/data
    environment:
      MINIO_ROOT_USER: mnusr
      MINIO_ROOT_PASSWORD: Strong#Pass#2024
    command: server --console-address ":9001" /data
    restart: on-failure:3
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://minio:9000/minio/health/ready"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
