services:
  telegram-review-bot:
    container_name: telegram-review-bot
    image: telegram-review-bot
    build:
      context: ./combined
      dockerfile: Dockerfile
    depends_on:
      - minio
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_SECURE=${MINIO_SECURE}
      - BOT_TOKEN=${BOT_TOKEN}

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./persistence/minio/:/data
    environment:
      MINIO_ACCESS_KEY: mnusr
      MINIO_SECRET_KEY: Strong#Pass#2024
    command: server --console-address ":9001" /data
    restart: on-failure:3
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://minio:9000/minio/health/ready"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
